name: Workflow 1
on: 
  workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code 
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: echo "Installing dependencies..."
      - name: Run linting
        run: npm run lint
      - name: Linting completed
        run: echo "Linting completed successfully!"

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code 
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install messages
        run: echo "Installing dependencies..."
      - name: Install dependencies
        run: npm ci
      - name: Test messages
        run: echo "Running tests..."
      - name: Run tests
        run: npm test
        
  deploy:
    needs: test 
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code 
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies messages
        run: echo "Installing dependencies..."
      - name: Install dependencies
        run: npm ci
      - name: Deploy the application message
        run: echo "Deploying the application..."
      - name: Build the application
        run: npm run build
